In [2]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
import numpy as np

In [5]:
np.shape(matrix)

(3, 3)

In [8]:
 temp = np.transpose(matrix)

In [10]:
print(temp)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
row = len(matrix)

In [12]:
column = len(matrix[0])

In [22]:
row = len(matrix)
column = len(matrix[0])
result = [[0]*row for i in range(column)]

for i in range(len(matrix)):
    for j in range(len(matrix[i])):
        result[j][i] = matrix[i][j]
        

In [20]:
result = [[0]*row for i in range(column)]

In [23]:
result

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]